<?php
define("BTN_COLOR",'btn');
define("SWATCH",'custom');
define("ENHANCED_STYLE",'');
define("STYLE_WIDTH",'');
define("BTN_SIZE",'small');
define("MENU_LOCATION",'static-top');
define("MENU_HEIGHT",'65');
define("MENU_WIDTH",'769');
define("MENU_ALIGN",'left');
define("FLYOUT_SIDEBAR",'0');
define("THEME_CUSTOM_LANGUAGE",'1');
?>