<?php
define("BTN_COLOR",'btn');
define("SWATCH",'');
define("ENHANCED_STYLE",'');
define("STYLE_WIDTH",'');
define("STYLE_COLOR",'color/violet.less');
define("BTN_SIZE",'small');
define("MENU_LOCATION",'fixed-top');
define("MENU_HEIGHT",'12');
define("MENU_WIDTH",'769');
define("MENU_ALIGN",'left');
define("FLYOUT_SIDEBAR",'1');
?>