<?php

return array(
	'modules/containermodule/actions/delete.php'=>'',
	'modules/containermodule/actions/edit.php'=>'',
	'modules/containermodule/actions/order.php'=>'',
	'modules/containermodule/actions/save.php'=>'',
	'modules/containermodule/actions/delete_content.php'=>'',
	'modules/containermodule/actions/orphans_modules.php'=>'',
	'modules/containermodule/actions/orphans_content.php'=>'',
	'modules/containermodule/class.php'=>'',
	'modules/containermodule/views/Default.tpl'=>'',
	'modules/containermodule/views/_sourcePicker.tpl'=>'',
	'modules/containermodule/views/_form_edit.tpl'=>'',
	'modules/containermodule/views/_nocontent.tpl'=>'',
	'modules/containermodule/views/_lastreferencedelete.tpl'=>'',
	'modules/containermodule/views/_orphans_modules.tpl'=>'',
	'datatypes/container.php'=>'',
	'datatypes/definitions/container.php'=>'',
	'datatypes/definitions/locationref.php'=>'',
	'datatypes/definitions/sectionref.php'=>'',
	'modules/containermodule/views/_linkPicker.tpl'=>'',
	'modules/containermodule/views/Grid - 2x2.tpl'=>'',
	'modules/containermodule/views/Three Column.tpl'=>'',
	'modules/containermodule/views/Two Column.tpl'=>'',
	'modules/containermodule/views/_container.tpl'=>'',
	'modules/containermodule/manifest.php'=>'',
	'modules/containermodule/nosourceselected.php'=>'',
	'modules/containermodule/picked_source.php'=>'',
	'js/ContainerSourceControl.js'=>'',
	'modules/containermodule/manifest.php'=>1,
	'modules/containermodule/deps.php'=>'',
	'modules/containermodule/views/_contentPicker.tpl'=>'',
);

?>