<?php
define("BTN_COLOR",'btn');
define("SWATCH",'united');
define("BTN_SIZE",'small');
define("MENU_LOCATION",'fixed-top');
define("MENU_HEIGHT",'1');
define("MENU_WIDTH",'769');
define("MENU_ALIGN",'left');
define("MENU_LENGTH",'2');
define("FLYOUT_SIDEBAR",'1');
define("THEME_CUSTOM_LANGUAGE",'0');
?>