<?php
define("BTN_COLOR",'btn');
define("SWATCH",'united');
define("BTN_SIZE",'small');
define("MENU_LOCATION",'fixed-top');
define("MENU_HEIGHT",'1');
define("MENU_WIDTH",'979');
define("MENU_ALIGN",'left');
?>