<?php
define("BTN_COLOR",'btn');
define("SWATCH",'');
define("ENHANCED_STYLE",'0');
define("ENHANCED_STYLE2",'0');
define("ENHANCED_STYLE3",'1');
define("ENHANCED_STYLE4",'1');
define("ENHANCED_STYLE5",'0');
define("ENHANCED_STYLE6",'1');
define("THEME_COLOR",'#0080c0');
define("STYLE_WIDTH",'');
define("BTN_SIZE",'small');
define("MENU_LOCATION",'fixed-top');
define("MENU_HEIGHT",'1');
define("MENU_WIDTH",'769');
define("MENU_ALIGN",'left');
define("MENU_LENGTH",'2');
define("FLYOUT_SIDEBAR",'1');
?>