<?php

return array(
	'modules/calendarmodule/actions/delete.php'=>'',
	'modules/calendarmodule/actions/edit.php'=>'',
	'modules/calendarmodule/actions/save.php'=>'',
	'modules/calendarmodule/actions/view.php'=>'',
	'modules/calendarmodule/actions/viewday.php'=>'',
	'modules/calendarmodule/actions/viewmonth.php'=>'',
	'modules/calendarmodule/actions/viewweek.php'=>'',
	'modules/calendarmodule/class.php'=>'',
	'modules/calendarmodule/views/Default.config'=>'',
	'modules/calendarmodule/views/Default.tpl'=>'',
	'modules/calendarmodule/views/Mini-Calendar.config'=>'',
	'modules/calendarmodule/views/Mini-Calendar.tpl'=>'',
	'modules/calendarmodule/views/Monthly.config'=>'',
	'modules/calendarmodule/views/Monthly.tpl'=>'',
	'modules/calendarmodule/views/Weekly.config'=>'',
	'modules/calendarmodule/views/Weekly.tpl'=>'',
	'modules/calendarmodule/views/_view.tpl'=>'',
	'modules/calendarmodule/views/_viewday.tpl'=>'',
	'modules/calendarmodule/views/_viewmonth.tpl'=>'',
	'modules/calendarmodule/views/_viewweek.tpl'=>'',
	'modules/calendarmodule/views/_workflowview.tpl'=>'',
	'modules/calendarmodule/views/_form_edit.tpl'=>'',
	'modules/calendarmodule/views/Monthly List.tpl'=>'',
	'modules/calendarmodule/views/Monthly List.config'=>'',
	'datatypes/calendar.php'=>'',
	'datatypes/definitions/calendar.info.php'=>'',
	'datatypes/definitions/calendar.php'=>'',
	'modules/calendarmodule/images/bottomcurve.gif'=>'',
	'modules/calendarmodule/images/topcurve.gif'=>'',
	'modules/calendarmodule/js/postedit.validate.js'=>'',
	'modules/calendarmodule/manifest.php'=>'1',
	'modules/calendarmodule/deps.php'=>'',
	'modules/calendarmodule/actions/delete_form.php'=>'',
	'modules/calendarmodule/actions/process_delete.php'=>'',
	'modules/calendarmodule/views/_form_delete.tpl'=>'',
	'modules/calendarmodule/views/_recur_dates.tpl'=>'',
	'modules/calendarmodule/form.part'=>'',
	'datatypes/definitions/eventdate.php'=>'',
	'modules/calendarmodule/actions/delete_process.php'=>'',
	'datatypes/eventdate.php'=>'',
	'modules/calendarmodule/actions/send_feedback.php'=>'',
	'modules/calendarmodule/views/Administration.tpl'=>'',
	'modules/calendarmodule/views/Default.form'=>'',
	'modules/calendarmodule/views/_cat_viewCategories.tpl'=>'',
	'modules/calendarmodule/views/_feedback_submitted.tpl'=>'',
	'modules/calendarmodule/views/Administration.config'=>'',
	'datatypes/definitions/calendarmodule_config.php'=>'',
	'datatypes/calendarmodule_config.php'=>'',
	'modules/calendarmodule/views/Past Events.tpl'=>'',
	'modules/calendarmodule/views/Upcoming Events.tpl'=>'',
	'modules/calendarmodule/views/Upcoming Events.config'=>'',
	'modules/calendarmodule/views/Upcoming Events.form'=>'',
	'modules/calendarmodule/views/Past Events.form'=>'',
	'modules/calendarmodule/views/Past Events.config'=>'',
	'modules/calendarmodule/views/Upcoming Events - Summary.form'=>'',
	'modules/calendarmodule/views/Upcoming Events - Summary.config'=>'',
	'modules/calendarmodule/views/Upcoming Events - Summary.tpl'=>'',
);

?>